"""start

Revision ID: 0001
Revises: 
Create Date: 2015-12-12 06:12:30.702361

"""

# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('server', sa.String(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('wcm_prefix', sa.String(), nullable=True),
    sa.Column('rfid_effective_time_s', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfid_config',
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('baudrate', sa.Integer(), nullable=True),
    sa.Column('bytesize', sa.Integer(), nullable=True),
    sa.Column('parity', sa.String(length=1), nullable=True),
    sa.Column('stopbits', sa.Float(), nullable=True),
    sa.Column('xonxoff', sa.Boolean(), nullable=True),
    sa.Column('rtscts', sa.Boolean(), nullable=True),
    sa.Column('dsrdtr', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_config_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('keep', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['master_config_id'], ['master_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_config',
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('baudrate', sa.Integer(), nullable=True),
    sa.Column('bytesize', sa.Integer(), nullable=True),
    sa.Column('parity', sa.String(length=1), nullable=True),
    sa.Column('stopbits', sa.Float(), nullable=True),
    sa.Column('xonxoff', sa.Boolean(), nullable=True),
    sa.Column('rtscts', sa.Boolean(), nullable=True),
    sa.Column('dsrdtr', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_config_id', sa.Integer(), nullable=True),
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('keep', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['master_config_id'], ['master_config.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['rfid_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfid_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('rfid', sa.BigInteger(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(), nullable=True),
    sa.Column('last_detected_at', sa.DateTime(), nullable=True),
    sa.Column('n_events', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reader_id'], ['rfid_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mass_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfid', sa.BigInteger(), nullable=True),
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('balance_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('mass_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['balance_id'], ['balance_config.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['rfid_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mass_event')
    op.drop_table('rfid_event')
    op.drop_table('balance_config')
    op.drop_table('rfid_config')
    op.drop_table('master_config')
    ### end Alembic commands ###
