"""balace

Revision ID: 0002
Revises: 0001
Create Date: 2015-12-14 11:43:33.714526

"""

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measurement_rate_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_mass_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('read_continuously', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('refload_mass_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('refload_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stability_n', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tolerance_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('zero_value', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_config', schema=None) as batch_op:
        batch_op.drop_column('zero_value')
        batch_op.drop_column('tolerance_kg')
        batch_op.drop_column('stability_n')
        batch_op.drop_column('refload_value')
        batch_op.drop_column('refload_mass_kg')
        batch_op.drop_column('read_continuously')
        batch_op.drop_column('min_mass_kg')
        batch_op.drop_column('measurement_rate_code')

    ### end Alembic commands ###
