"""balace

Revision ID: 0003
Revises: 0002
Create Date: 2015-12-14 12:06:35.003577

"""

# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measurement_rate_hz', sa.Integer(), nullable=True))
        batch_op.drop_column('measurement_rate_code')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measurement_rate_code', sa.INTEGER(), nullable=True))
        batch_op.drop_column('measurement_rate_hz')

    ### end Alembic commands ###
