#!/bin/bash

THIS_SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_BASE=`readlink -m "$THIS_SCRIPT_DIR/.."`

N_SEQUENCE_CHARS=4  # like Django

# Check syntax
if [ "$1" == "" ]; then
    echo "Syntax:"
    echo "   $0 \"comment\""
    exit 1
fi

# Find latest revision
ALEMBIC_VERSIONS_DIR=$PROJECT_BASE/starfeeder/alembic/versions
CURRENT_SEQ=`find "$ALEMBIC_VERSIONS_DIR" -type f -name "*.py" -printf "%f\n" | cut -c 1-$N_SEQUENCE_CHARS | sort | tail -n 1`
# echo "Current sequence number: $CURRENT_SEQ"
if [ "$CURRENT_SEQ" = "" ]; then
    CURRENT_SEQ=0
fi
echo "Current sequence number: $CURRENT_SEQ"

# Add one
NEW_SEQ=$((CURRENT_SEQ + 1))
# Add leading zeros
printf -v NEW_SEQ "%0${N_SEQUENCE_CHARS}d" $NEW_SEQ
echo "    New sequence number: $NEW_SEQ"

export PYTHONPATH=$PROJECT_BASE
echo "Generating new revision with Alembic..."
echo "    [If it fails with \"Can't locate revision identified by...\", you might need to DROP the alembic_version table.]"
cd "$PROJECT_BASE/starfeeder"
alembic revision --autogenerate -m $1 --rev-id $NEW_SEQ

#VERSION_PY_STEM=starfeeder/alembic/current_revision.py
#VERSION_PY_FILE="$PROJECT_BASE/$VERSION_PY_STEM"
#echo "Creating $VERSION_PY_FILE"
#cat << END_HEREDOC > "$VERSION_PY_FILE"
##!/usr/bin/env python3
## $VERSION_PY_STEM
## AUTOGENERATED by create_database_migration.sh; do not edit.
#
#ALEMBIC_CURRENT_REVISION = "$NEW_SEQ"
#END_HEREDOC
