######################################################################
# Automatically generated by qmake (3.0) Tue Dec 8 12:41:46 2015
######################################################################

TEMPLATE = app
TARGET = bugtest
INCLUDEPATH += .

# Input
SOURCES += bugtest_qt_signal_derived.cpp
HEADERS += bugtest_qt_signal_derived.h
